[application]
host = "0.0.0.0"
port = 9090
open_weather_api_key =

[email]
to_address = 
username = 
password = 

[database]
host = 
port = 
username = "postgres"
password = 
database_name = "aurora_alert"